import { Component, OnInit } from '@angular/core';
import { VehicleService } from './services/vehicle.service';
import { LoadingService } from './services/loading/loading.service';
import { AuthService } from './services/Auth/auth.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  constructor(
    public vehicleService: VehicleService,
    public loadingService: LoadingService,
    public authService: AuthService,
  ) {}
  vehicles: any[] = []; // Сюди прийдуть дані з Firebase

  ngOnInit() {
    // Тимчасово, щоб наповнити базу
    const initialVehicles = [
      {
        id: 1,
        name: 'Audi A4',
        plate: 'AO 100 E',
        consumption: 6.8,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 2,
        name: 'Skoda Kodiaq',
        plate: 'AO 101 E',
        consumption: 8.8,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 3,
        name: 'Mitsubishi Outlander',
        plate: 'AO 103 E',
        consumption: 8.1,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 4,
        name: 'Opel Astra',
        plate: 'AO 104 E',
        consumption: 7.5,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 5,
        name: 'Fiat Talento',
        plate: 'AO 105 E',
        consumption: 9.0,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 6,
        name: 'Skoda Octavia',
        plate: 'AO 107 E',
        consumption: 9.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 7,
        name: 'ГАЗ 2705',
        plate: 'AO 109 E',
        consumption: 15.0,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 8,
        name: 'Renault Duster',
        plate: 'AO 111 E',
        consumption: 7.7,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 9,
        name: 'Volkswagen T6',
        plate: 'AO 123 E',
        consumption: 9.0,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 10,
        name: 'Ssang Yong Musso',
        plate: 'AO 194 E',
        consumption: 8.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 11,
        name: 'Mercedes 815',
        plate: 'AO 270 E',
        consumption: 19.8,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 12,
        name: 'Volkswagen Passat',
        plate: 'AO 302 E',
        consumption: 6.6,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 13,
        name: 'Volkswagen Golf',
        plate: 'AO 303 E',
        consumption: 6.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 14,
        name: 'Volkswagen Golf',
        plate: 'AO 305 E',
        consumption: 6.5,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 15,
        name: 'Ssang Yong Musso',
        plate: 'AO 321 E',
        consumption: 12.0,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 16,
        name: 'Ssang Yong Musso',
        plate: 'AO 322 E',
        consumption: 8.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 17,
        name: 'Toyota Land Cruiser 150',
        plate: 'AO 329 E',
        consumption: 12.2,
        mileage: 108525,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 18,
        name: 'Hyundai Tucson',
        plate: 'AO 305 E',
        consumption: 8.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 19,
        name: 'ГАЗ 31105',
        plate: 'AO 011 E',
        consumption: 10.5,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 20,
        name: 'Ssang Yong Musso',
        plate: 'AO 037 E',
        consumption: 8.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 21,
        name: 'ВАЗ (Lada)',
        plate: 'AO 044 E',
        consumption: 7.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 22,
        name: 'Audi A6',
        plate: 'AO 050 E',
        consumption: 12.7,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 23,
        name: 'Volkswagen B5 (Passat)',
        plate: 'AO 102 E',
        consumption: 10.0,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 24,
        name: 'Audi A4',
        plate: 'AO 110 E',
        consumption: 12.3,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 25,
        name: 'Volkswagen Golf',
        plate: 'AO 157 E',
        consumption: 6.5,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 26,
        name: 'Skoda Fabia',
        plate: 'AO 226 E',
        consumption: 7.0,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
      {
        id: 27,
        name: 'Mercedes Benz',
        plate: 'AO 246 E',
        consumption: 9.2,
        mileage: 0,
        fuelLeft: 0,
        history: [],
      },
    ];

    // якщо треба дані відправити у firebase
    // this.vehicleService.initDatabase(initialVehicles);
    // 2. ОСЬ ТУТ ПІДПИСУЄМОСЯ НА ОНОВЛЕННЯ
    this.vehicleService.getVehicles().subscribe((data) => {
      this.vehicles = data;
      console.log('Дані з Firebase отримано:', this.vehicles);
    });
  }
}
